<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EDCSuiteRedux.Core\EDCSuiteRedux.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPFHexaEditor" Version="3.4.5" />
  </ItemGroup>
</Project>